= Tatami: TiddlyWiki Starter

A Node.js-based, styled, and batteries-included TiddlyWiki starter template configured for external images and binary assets, making it ready for image-heavy workflows.

== Prerequisites

Install the TiddlyWiki Node.js package/CLI globally:

https://tiddlywiki.com/static/Installing%2520TiddlyWiki%2520on%2520Node.js.html

== Usage

To run the wiki:

[source,bash]
----
tiddlywiki tatami --listen port=8085 root-tiddler=$$:/core/save/lazy-images 
----

... or use the included Makefile.

This will serve the wiki on http://localhost:8085

== Included Plugins

* Disclosure HTML element: DetailsWidget `$:/plugins/telmiger/details`
* Edit Buttons: Save & close / Cancel & close / Save & keep open `$:/plugins/telmiger/EditButtons`
* ImportToExternalFile: Save binary files to the files folder on node.js `$:/plugins/sq/ImportToExternalFile`
* Kara: Small plain checklist and interstitial journaling `$:/plugins/kookma/kara`
* MathyThing: Some basic math operations for TiddlyWiki `$:/plugins/inmysocks/MathyThing`
* Projectify: Simple project management in TiddlyWiki `$:/plugins/nico/projectify`
* Refnotes: References, citations, footnotes and abbreviations in Tiddlywiki `$:/plugins/kookma/refnotes`
* Relink Titles: Renames tiddlers with titles derived from Relinked tiddler `$:/plugins/flibbles/relink-titles`
* Relink: Flexibility when relinking renamed tiddlers `$:/plugins/flibbles/relink`
* Shiraz Callout: Admonitions for Shiraz `$:/plugins/kookma/shiraz-callout`
* TiddlyFormula: Spreadsheet-like formulas in TiddlyWiki. `$:/plugins/ebalster/formula`
* Utility: Small tools for authors and developers `$:/plugins/kookma/utility`
* shuffle: A Shuffle filter operator `$:/plugins/mklauber/shuffle`
* tiddlystudy-references: bidirectional linking `$:/plugins/kebi/tiddlystudy-references`
* tw-fountain: Fountain screenplay support `$:/plugins/tm/tw-fountain`

